/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizzify;

import java.util.ArrayList;
import java.util.List;
import util.Operation;
import util.Question;
import util.Quiz;

/**
 *
 * @author maya1
 */
public class EditQuizUI extends javax.swing.JFrame {

    Quiz quiz;

    /**
     * Creates new form EditQuizUI
     *
     * @param quiz
     */
    public EditQuizUI(Quiz quiz) {
        initComponents();
        this.quiz = quiz;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        closeLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        option2Label = new javax.swing.JLabel();
        option3Label = new javax.swing.JLabel();
        option1Label = new javax.swing.JLabel();
        option4Label = new javax.swing.JLabel();
        tfAnswerTwo = new javax.swing.JTextField();
        tfAnswerOne1 = new javax.swing.JTextField();
        tfAnswerThree = new javax.swing.JTextField();
        tfAnswerOne2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblCorrectAnswer = new javax.swing.JLabel();
        optionsComboBox = new javax.swing.JComboBox<>();
        btnPreviousQuestion = new javax.swing.JButton();
        btnNextQuestion = new javax.swing.JButton();
        btnNewQuestion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Question");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("...");

        closeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Close_100px_22.png"))); // NOI18N
        closeLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLblMouseClicked(evt);
            }
        });

        option2Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        option2Label.setText("Option 2");

        option3Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        option3Label.setText("Option 3");

        option1Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        option1Label.setText("Option 1");

        option4Label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        option4Label.setText("Option 4");

        lblCorrectAnswer.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        lblCorrectAnswer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCorrectAnswer.setText("Correct Answer");

        optionsComboBox.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        String[] answerOptions = { "Option 1", "Option 2", "Option 3", "Option 4" };
        optionsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(answerOptions));

        btnPreviousQuestion.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnPreviousQuestion.setText("Previous");

        btnNextQuestion.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnNextQuestion.setText("Next");

        btnNewQuestion.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnNewQuestion.setText("New Question");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeLbl))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(option2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(option3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfAnswerTwo, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addComponent(tfAnswerThree)
                    .addComponent(tfAnswerOne2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAnswerOne1))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(optionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnPreviousQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnNextQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNewQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addComponent(closeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(option1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(tfAnswerOne2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAnswerTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfAnswerThree)
                    .addComponent(option3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAnswerOne1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorrectAnswer)
                    .addComponent(optionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnPreviousQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNextQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewQuestion))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Option2RadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option2RadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Option2RadioBtnActionPerformed

    private void CloseProgressReportbttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseProgressReportbttnMouseClicked
        this.dispose();
    }//GEN-LAST:event_CloseProgressReportbttnMouseClicked

    private void closeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLblMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Quiz newQuiz = new Quiz();
        newQuiz.setSubject("Social Studies");
        newQuiz.setTitle("Planets");
        newQuiz.saveQuiz(1);
        
        List<String> optionsForQuestion1 = new ArrayList<>();
        optionsForQuestion1.add("Jupiter");
        optionsForQuestion1.add("Saturn");
        optionsForQuestion1.add("Mars");
        optionsForQuestion1.add("Uranus");

        Question question1 = new Question("What is the largest planet in our solar system?", optionsForQuestion1, 0);        

        List<String> optionsForQuestion2 = new ArrayList<>();
        optionsForQuestion2.add("Venus");
        optionsForQuestion2.add("Saturn");
        optionsForQuestion2.add("Mars");
        optionsForQuestion2.add("Mercury");

        Question question2 = new Question("Which of these is not a Planet", optionsForQuestion2, 0);

        List<String> optionsForQuestion3 = new ArrayList<>();
        optionsForQuestion3.add("Earth");
        optionsForQuestion3.add("Pluto");
        optionsForQuestion3.add("Mars");
        optionsForQuestion3.add("Jupiter");

        Question question3 = new Question("What is the largest planet in our solar system?", optionsForQuestion3, 0);
        question1.saveToDatabase(newQuiz.getQuizID());
        newQuiz.addQuestion(question1);
        question2.saveToDatabase(newQuiz.getQuizID());
        newQuiz.addQuestion(question2);
        question3.saveToDatabase(newQuiz.getQuizID());
        newQuiz.addQuestion(question3);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditQuizUI(newQuiz).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewQuestion;
    private javax.swing.JButton btnNextQuestion;
    private javax.swing.JButton btnPreviousQuestion;
    private javax.swing.JLabel closeLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCorrectAnswer;
    private javax.swing.JLabel option1Label;
    private javax.swing.JLabel option2Label;
    private javax.swing.JLabel option3Label;
    private javax.swing.JLabel option4Label;
    private javax.swing.JComboBox<String> optionsComboBox;
    private javax.swing.JTextField tfAnswerOne1;
    private javax.swing.JTextField tfAnswerOne2;
    private javax.swing.JTextField tfAnswerThree;
    private javax.swing.JTextField tfAnswerTwo;
    // End of variables declaration//GEN-END:variables
}
