/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package quizzify;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import util.Operation;

/**
 *
 * @author austi
 */
public class ResultStudent extends javax.swing.JInternalFrame {

    Operation O = new Operation();
    boolean view = false;
    double EngR, SciR, SoStR;
    double EngS, SciS, SoStS;

    public ResultStudent() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topLabel = new javax.swing.JLabel();
        studIDlabel = new javax.swing.JLabel();
        StudIDfield = new javax.swing.JTextField();
        checkButton = new javax.swing.JButton();
        englishLabel = new javax.swing.JLabel();
        ScienceLabel = new javax.swing.JLabel();
        SSTlabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EnglishResultField = new javax.swing.JTextField();
        ScienceResultField = new javax.swing.JTextField();
        SSTResultField = new javax.swing.JTextField();
        TotalField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EngBox = new javax.swing.JComboBox<>();
        SciBox = new javax.swing.JComboBox<>();
        SoStBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 51));
        setMinimumSize(new java.awt.Dimension(1100, 670));
        setPreferredSize(new java.awt.Dimension(1100, 670));

        jPanel1.setBackground(new java.awt.Color(255, 255, 130));

        topLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        topLabel.setText("Student Progress");

        studIDlabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        studIDlabel.setText("Student ID:");

        StudIDfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                StudIDfieldFocusGained(evt);
            }
        });

        checkButton.setBackground(new java.awt.Color(255, 255, 255));
        checkButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        checkButton.setText("Check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        englishLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        englishLabel.setText("English:");

        ScienceLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ScienceLabel.setText("Science:");

        SSTlabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        SSTlabel.setText("Social Studies:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("Quiz ID");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setText("Quiz ID");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setText("Quiz ID");

        EnglishResultField.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        EnglishResultField.setForeground(new java.awt.Color(153, 0, 153));
        EnglishResultField.setFocusable(false);

        ScienceResultField.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        ScienceResultField.setForeground(new java.awt.Color(153, 0, 153));
        ScienceResultField.setFocusable(false);

        SSTResultField.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        SSTResultField.setForeground(new java.awt.Color(153, 0, 153));
        SSTResultField.setFocusable(false);

        TotalField.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        TotalField.setForeground(new java.awt.Color(204, 0, 0));
        TotalField.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("Total:");

        EngBox.setModel(new javax.swing.DefaultComboBoxModel<>(O.quizIDList(1)));
        EngBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngBoxActionPerformed(evt);
            }
        });

        SciBox.setModel(new javax.swing.DefaultComboBoxModel<>(O.quizIDList(2)));
        SciBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SciBoxActionPerformed(evt);
            }
        });

        SoStBox.setModel(new javax.swing.DefaultComboBoxModel<>(O.quizIDList(3)));
        SoStBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoStBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(topLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(englishLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(EngBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(EnglishResultField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(113, 113, 113)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ScienceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ScienceResultField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SciBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(112, 112, 112)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SSTlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SSTResultField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SoStBox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(studIDlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkButton)
                                    .addComponent(StudIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(topLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studIDlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(checkButton)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(englishLabel)
                        .addComponent(ScienceLabel))
                    .addComponent(SSTlabel))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(EngBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(SciBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EnglishResultField)
                            .addComponent(ScienceResultField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(SoStBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SSTResultField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addGap(1, 1, 1)
                .addComponent(TotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        int StudID;
        view = true;
        String Eng, Sci, SoSt;
        String[] QuizID = new String[3];
        

        if (StudIDfield.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please Enter Student ID number");
        } 
        else {
            try {      
                    StudID = Integer.valueOf(StudIDfield.getText());
                    QuizID[0] = String.valueOf(EngBox.getSelectedItem());
                    QuizID[1] = String.valueOf(SciBox.getSelectedItem());
                    QuizID[2] = String.valueOf(SoStBox.getSelectedItem());

                    if (QuizID[0] == "Average" || QuizID[0] == "Total"){
                        EngS = Math.round(O.getResult(StudID, QuizID[0], 1)*100.0)/100.0;
                        Eng = String.valueOf(EngS);
                    }
                    else {
                        EngR = Math.round(O.getResult(StudID, QuizID[0])*100.0)/100.0;
                        Eng = String.valueOf(EngR) + "/10";
                    }
                    if (QuizID[1] == "Average" || QuizID[1] == "Total"){
                        SciS = Math.round(O.getResult(StudID, QuizID[1], 2)*100.0)/100.0;
                        Sci = String.valueOf(SciS);
                    }
                    else {
                        SciR = Math.round(O.getResult(StudID, QuizID[1], 2)*100.0)/100.0;
                        Sci = String.valueOf(SciR) + "/10";
                    }
                    if (QuizID[2] == "Average" || QuizID[2] == "Total"){
                        SoStS = Math.round(O.getResult(StudID, QuizID[2], 1)*100.0)/100.0;
                        SoSt = String.valueOf(SoStS);
                    }
                    else {
                        SoStR = Math.round(O.getResult(StudID, QuizID[2])*100.0)/100.0;
                        SoSt = String.valueOf(SoStR) + "/10";
                    }
                    EnglishResultField.setText(Eng);
                    ScienceResultField.setText(Sci);
                    SSTResultField.setText(SoSt);
                
            } 
            catch (NumberFormatException ex){
                JOptionPane.showMessageDialog(this,"Please Enter Correct Student ID number");
            }
        }
        
        
    }//GEN-LAST:event_checkButtonActionPerformed

    private void EngBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngBoxActionPerformed
        if (view == true) {
            int StudID;
            String QuizID;

            StudID = Integer.valueOf(StudIDfield.getText());
            QuizID = String.valueOf(EngBox.getSelectedItem());

            EngR = Math.round(O.getResult(StudID, QuizID)*100.0)/100.0;
            EngS = Math.round(O.getResult(StudID, QuizID, 1)*100.0)/100.0;

            if (QuizID == "Average" || QuizID == "Total")
                EnglishResultField.setText(String.valueOf(EngS));
            else 
                EnglishResultField.setText(String.valueOf(EngR)  + "/10");
        }
    }//GEN-LAST:event_EngBoxActionPerformed

    private void SciBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SciBoxActionPerformed
        if (view == true) {
            int StudID;
            String QuizID;

            StudID = Integer.valueOf(StudIDfield.getText());
            QuizID = String.valueOf(SciBox.getSelectedItem());

            SciR = Math.round(O.getResult(StudID, QuizID)*100.0)/100.0;
            SciS = Math.round(O.getResult(StudID, QuizID, 2)*100.0)/100.0;
                        
            if (QuizID == "Average" || QuizID == "Total")
                ScienceResultField.setText(String.valueOf(SciS));
            else
                ScienceResultField.setText(String.valueOf(SciR)  + "/10");
        }
    }//GEN-LAST:event_SciBoxActionPerformed

    private void SoStBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoStBoxActionPerformed
        if (view == true) {
            int StudID;
            String QuizID;

            StudID = Integer.valueOf(StudIDfield.getText());
            QuizID = String.valueOf(SoStBox.getSelectedItem());

            SoStR = Math.round(O.getResult(StudID, QuizID)*100.0)/100.0;
            SoStS = Math.round(O.getResult(StudID, QuizID, 3)*100.0)/100.0;

            if (QuizID == "Average" || QuizID == "Total")
                SSTResultField.setText(String.valueOf(SoStS));
            else
                SSTResultField.setText(String.valueOf(SoStR)  + "/10");
        }
    }//GEN-LAST:event_SoStBoxActionPerformed

    private void StudIDfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_StudIDfieldFocusGained
        view = false;
        StudIDfield.setText(""); 
    }//GEN-LAST:event_StudIDfieldFocusGained

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EngBox;
    private javax.swing.JTextField EnglishResultField;
    private javax.swing.JTextField SSTResultField;
    private javax.swing.JLabel SSTlabel;
    private javax.swing.JComboBox<String> SciBox;
    private javax.swing.JLabel ScienceLabel;
    private javax.swing.JTextField ScienceResultField;
    private javax.swing.JComboBox<String> SoStBox;
    private javax.swing.JTextField StudIDfield;
    private javax.swing.JTextField TotalField;
    private javax.swing.JButton checkButton;
    private javax.swing.JLabel englishLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel studIDlabel;
    private javax.swing.JLabel topLabel;
    // End of variables declaration//GEN-END:variables
}
