/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizzify;

import java.awt.Color;

import util.Operation;

import javax.swing.*;

/**
 *
 * @author bethe
 */
public class TakeQuiz extends JFrame {

    /**
     * Creates new form TakeQuiz
     */

    String userType = "Stud";
    int count = 0;
    // String QID = "";
    Operation O = new Operation();
    int quizID = O.getQuizCache();

    Color DefaultColour, ClickedColour, DefaultInnerColour, ClickedInnerColour;
    
    public TakeQuiz() {
        initComponents();
        DefaultColour= new Color(230,196,70);
        DefaultInnerColour = new Color(230,208,112);
        ClickedColour = new Color(204,102,255);
        ClickedInnerColour= new Color(219,147,255);


        String[] Detail = O.questionDetails(quizID, count);
            Question.setText(Detail[0]);
            OptA.setText(Detail[1]);
            OptB.setText(Detail[2]);
            OptC.setText(Detail[3]);
        count++;

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PreviousButton = new javax.swing.JButton();
        OptionA = new javax.swing.JPanel();
        OptA = new javax.swing.JLabel();
        OptionB = new javax.swing.JPanel();
        OptB = new javax.swing.JLabel();
        OptionC = new javax.swing.JPanel();
        OptC = new javax.swing.JLabel();
        OptionD = new javax.swing.JPanel();
        OptD = new javax.swing.JLabel();
        SkipButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Question = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        logoLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PreviousButton.setBackground(new java.awt.Color(255, 255, 255));
        PreviousButton.setText("Previous");
        PreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousButtonActionPerformed(evt);
            }
        });

        OptionA.setBackground(new java.awt.Color(230, 196, 70));
        OptionA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OptionAMousePressed(evt);
            }
        });

        OptA.setBackground(new java.awt.Color(230, 208, 112));
        OptA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        OptA.setText("Title of the Quiz");
        OptA.setOpaque(true);

        javax.swing.GroupLayout OptionALayout = new javax.swing.GroupLayout(OptionA);
        OptionA.setLayout(OptionALayout);
        OptionALayout.setHorizontalGroup(
            OptionALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OptA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        OptionALayout.setVerticalGroup(
            OptionALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OptA, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        OptionB.setBackground(new java.awt.Color(230, 196, 70));
        OptionB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OptionBMousePressed(evt);
            }
        });

        OptB.setBackground(new java.awt.Color(230, 208, 112));
        OptB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        OptB.setText("Title of the Quiz");
        OptB.setOpaque(true);

        javax.swing.GroupLayout OptionBLayout = new javax.swing.GroupLayout(OptionB);
        OptionB.setLayout(OptionBLayout);
        OptionBLayout.setHorizontalGroup(
            OptionBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OptB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        OptionBLayout.setVerticalGroup(
            OptionBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OptB, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        OptionC.setBackground(new java.awt.Color(230, 196, 70));
        OptionC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OptionCMousePressed(evt);
            }
        });

        OptC.setBackground(new java.awt.Color(230, 208, 112));
        OptC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        OptC.setText("Title of the Quiz");
        OptC.setOpaque(true);

        javax.swing.GroupLayout OptionCLayout = new javax.swing.GroupLayout(OptionC);
        OptionC.setLayout(OptionCLayout);
        OptionCLayout.setHorizontalGroup(
            OptionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OptC, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );
        OptionCLayout.setVerticalGroup(
            OptionCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OptC, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        OptionD.setBackground(new java.awt.Color(230, 196, 70));
        OptionD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OptionDMousePressed(evt);
            }
        });

        OptD.setBackground(new java.awt.Color(230, 208, 112));
        OptD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        OptD.setText("Title of the Quiz");
        OptD.setOpaque(true);

        javax.swing.GroupLayout OptionDLayout = new javax.swing.GroupLayout(OptionD);
        OptionD.setLayout(OptionDLayout);
        OptionDLayout.setHorizontalGroup(
            OptionDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OptD, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );
        OptionDLayout.setVerticalGroup(
            OptionDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OptD, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        SkipButton.setBackground(new java.awt.Color(255, 255, 255));
        SkipButton.setText("Skip");
        SkipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkipButtonActionPerformed(evt);
            }
        });

        NextButton.setBackground(new java.awt.Color(255, 255, 255));
        NextButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(204, 102, 255));

        Question.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Question.setText("Quiestion");

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel14.setText("No.");

        logoLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Question, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PreviousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(SkipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(OptionA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OptionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NextButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(OptionB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OptionD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OptionA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OptionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OptionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OptionD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PreviousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SkipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousButtonActionPerformed
        String[] Detail = O.questionDetails(quizID, count - 2);
            Question.setText(Detail[0]);
            OptA.setText(Detail[1]);
            OptB.setText(Detail[2]);
            OptC.setText(Detail[3]);
            OptD.setText(Detail[4]);
        count++;
    }//GEN-LAST:event_PreviousButtonActionPerformed

    private void OptionAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionAMousePressed
        OptionA.setBackground(ClickedColour);
        OptionB.setBackground(DefaultColour);
        OptionC.setBackground(DefaultColour);
        OptionD.setBackground(DefaultColour);

        OptA.setBackground(ClickedInnerColour);
        OptB.setBackground(DefaultInnerColour);
        OptC.setBackground(DefaultInnerColour);
        OptD.setBackground(DefaultInnerColour);

    }//GEN-LAST:event_OptionAMousePressed

    private void OptionBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionBMousePressed
        OptionA.setBackground(DefaultColour);
        OptionB.setBackground(ClickedColour);
        OptionC.setBackground(DefaultColour);
        OptionD.setBackground(DefaultColour);


        OptA.setBackground(DefaultInnerColour);
        OptB.setBackground(ClickedInnerColour);
        OptC.setBackground(DefaultInnerColour);
        OptD.setBackground(DefaultInnerColour);
    }//GEN-LAST:event_OptionBMousePressed

    private void OptionCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionCMousePressed
        OptionA.setBackground(DefaultColour);
        OptionB.setBackground(DefaultColour);
        OptionC.setBackground(ClickedColour);
        OptionD.setBackground(DefaultColour);

        OptA.setBackground(DefaultInnerColour);
        OptB.setBackground(DefaultInnerColour);
        OptC.setBackground(ClickedInnerColour);
        OptD.setBackground(DefaultInnerColour);
    }//GEN-LAST:event_OptionCMousePressed

    private void OptionDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionDMousePressed
        OptionA.setBackground(DefaultColour);
        OptionB.setBackground(DefaultColour);
        OptionC.setBackground(DefaultColour);
        OptionD.setBackground(ClickedColour);

        OptA.setBackground(DefaultInnerColour);
        OptB.setBackground(DefaultInnerColour);
        OptC.setBackground(DefaultInnerColour);
        OptD.setBackground(ClickedInnerColour);
    }//GEN-LAST:event_OptionDMousePressed

    private void SkipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkipButtonActionPerformed

        String[] Detail = O.questionDetails(quizID, count);
            Question.setText(Detail[0]);
            OptA.setText(Detail[1]);
            OptB.setText(Detail[2]);
            OptC.setText(Detail[3]);
            OptD.setText(Detail[4]);
        count++;
    }//GEN-LAST:event_SkipButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        String[] Detail = O.questionDetails(quizID, count);
            Question.setText(Detail[0]);
            OptA.setText(Detail[1]);
            OptB.setText(Detail[2]);
            OptC.setText(Detail[3]);
            OptD.setText(Detail[4]);
        count++;
    }//GEN-LAST:event_NextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextButton;
    private javax.swing.JLabel OptA;
    private javax.swing.JLabel OptB;
    private javax.swing.JLabel OptC;
    private javax.swing.JLabel OptD;
    private javax.swing.JPanel OptionA;
    private javax.swing.JPanel OptionB;
    private javax.swing.JPanel OptionC;
    private javax.swing.JPanel OptionD;
    private javax.swing.JButton PreviousButton;
    private javax.swing.JLabel Question;
    private javax.swing.JButton SkipButton;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel logoLabel6;
    // End of variables declaration//GEN-END:variables
}
